// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/projects/*": {
    params: {
      "*": string;
    };
  };
  "/projects/*/:projectId": {
    params: {
      "projectId": string;
    };
  };
  "/contact": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/projects/*" | "/projects/*/:projectId" | "/contact";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/projects.tsx": {
    id: "routes/projects";
    page: "/projects/*" | "/projects/*/:projectId";
  };
  "routes/projects/index.tsx": {
    id: "routes/projects/index";
    page: "/projects/*";
  };
  "routes/projects/$projectId.tsx": {
    id: "routes/projects/$projectId";
    page: "/projects/*/:projectId";
  };
  "routes/contact.tsx": {
    id: "routes/contact";
    page: "/contact";
  };
};